export const COLORS = {
  light: {
    background: "#f7f9fb",
    onBackground: "#191c1e",
    surface: "#f7f9fb",
    onSurface: "#191c1e",
    surfaceVariant: "#e0e3e5",
    onSurfaceVariant: "#434655",
    primary: "#004ac6",
    onPrimary: "#ffffff",
    primaryContainer: "#2563eb",
    onPrimaryContainer: "#eeefff",
    borderSubtle: "#E2E8F0",
    orpHighlight: "#EF4444",
    readerSepia: "#F4ECD8",
  },
  dark: {
    background: "#0B0E14",
    onBackground: "#eff1f3",
    surface: "#0B0E14",
    onSurface: "#eff1f3",
    surfaceVariant: "#2d3133",
    onSurfaceVariant: "#c3c6d7",
    primary: "#b4c5ff",
    onPrimary: "#00174b",
    primaryContainer: "#003ea8",
    onPrimaryContainer: "#dbe1ff",
    borderSubtle: "#3f465c",
    orpHighlight: "#EF4444",
    readerSepia: "#F4ECD8",
  },
};
